"""Delivering a one-time code.

A port because the product must be runnable, and testable, without a paid account. The mock
implementation is the default in development, and refuses to start in production — a guard
that belongs in the adapter, but which is stated here because it is part of the contract.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from letmehandle.domain.models.phone_number import PhoneNumber


class OTPProvider(ABC):
    """Sends a code to a number."""

    @property
    @abstractmethod
    def name(self) -> str:
        """What this provider is called, for logs and for readiness."""

    @property
    @abstractmethod
    def is_safe_for_production(self) -> bool:
        """Whether this provider actually delivers to a real handset.

        A mock answers false, and the application refuses to start in production with one
        configured. The failure mode being prevented is silent and total: everybody can sign
        in as anybody.
        """

    @property
    def fixed_code(self) -> str | None:
        """A code every challenge uses instead of a random one, or None for a random one.

        FOR TESTING ONLY. A provider that delivers nowhere offers one so that somebody running
        the app can sign in without reading the backend log. Only a provider that is not safe
        for production may offer one; the authentication service refuses a fixed code from any
        other, so a real provider cannot turn every account's code into a constant by accident.
        """
        return None

    @abstractmethod
    async def send(self, number: PhoneNumber, code: str) -> None:
        """Deliver the code, or raise `UnreachableNumberError` or `ProviderError`.

        The code is generated by the application, not by the provider, so that its length,
        alphabet and expiry are the product's decisions rather than a vendor's (D-036).

        `UnreachableNumberError` is for a number the provider will not deliver to, which the person
        signing in can correct. Anything else — throttled, down, refused credentials — is a
        `ProviderError` saying whether another attempt could help.
        """
