"""Delivering a one-time code.

A port because the product must be runnable, and testable, without a paid account. The mock
implementation is the default in development, and refuses to start in production — a guard
that belongs in the adapter, but which is stated here because it is part of the contract.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from letmehandle.domain.models.phone_number import PhoneNumber


class OTPProvider(ABC):
    """Sends a code to a number."""

    @property
    @abstractmethod
    def name(self) -> str:
        """What this provider is called, for logs and for readiness."""

    @property
    @abstractmethod
    def is_safe_for_production(self) -> bool:
        """Whether this provider actually delivers to a real handset.

        A mock answers false, and the application refuses to start in production with one
        configured. The failure mode being prevented is silent and total: everybody can sign
        in as anybody.
        """

    @abstractmethod
    async def send(self, number: PhoneNumber, code: str) -> None:
        """Deliver the code, or raise `ProviderError`.

        The code is generated by the application, not by the provider, so that its length,
        alphabet and expiry are the product's decisions rather than a vendor's.
        """
