#!/usr/bin/env python3
"""Write the configuration reference from the settings definition, and check what copies it.

`Settings` in `apps/backend/src/letmehandle/config/settings.py` is the only place the backend reads
its environment. Three other files repeat what it declares, and each drifts the moment somebody
adds a variable and forgets one of them:

- `docs/development/configuration.md`, the reference, which this script writes;
- `.env.example`, which must list every variable and nothing else but the stack's own ports;
- `docker-compose.yml`, whose backend must be handed every variable, or setting one in `.env`
  silently does nothing in the development stack.

`--check` writes nothing and fails naming each difference. `make verify` runs it.
"""

from __future__ import annotations

import argparse
import re
import sys
from enum import Enum
from pathlib import Path
from types import NoneType, UnionType
from typing import TYPE_CHECKING, Final, Union, get_args, get_origin

from annotated_types import Ge, Gt, Le, Lt
from pydantic import SecretStr

if TYPE_CHECKING:
    from pydantic.fields import FieldInfo

ROOT: Final = Path(__file__).resolve().parents[1]
BACKEND: Final = ROOT / "apps" / "backend"
REFERENCE: Final = ROOT / "docs" / "development" / "configuration.md"
ENV_EXAMPLE: Final = ROOT / ".env.example"
COMPOSE: Final = ROOT / "docker-compose.yml"

sys.path.insert(0, str(BACKEND / "src"))

# Read by the Makefile and docker-compose.yml to choose host ports, never by the backend, which
# listens on 8000 inside its container whatever these say.
STACK_VARIABLES: Final = {
    "BACKEND_PORT": "Host port the development stack publishes the backend on. Default `8000`.",
    "POSTGRES_PORT": "Host port the development stack publishes PostgreSQL on. Default `5432`.",
}

HEADER: Final = """\
# Configuration reference

<!-- Generated by scripts/generate_config_reference.py from the settings definition. Do not edit:
     change `Settings` in apps/backend/src/letmehandle/config/settings.py and run
     `make config-reference`. `make verify` fails when this file is out of date. -->

Every variable the backend reads, from `Settings` in
[`apps/backend/src/letmehandle/config/settings.py`](../../apps/backend/src/letmehandle/config/settings.py).
Nothing else in the codebase reads the environment. Values come from the process environment,
then from a `.env` file in the working directory.

**Required** says when a variable must be set; the process refuses to start, naming it, when a
feature that needs it is configured without it. A blank value is the same as an unset one.
**Secret** variables are never logged or rendered in an error. The narrative for each, with
examples, is in [`.env.example`](../../.env.example).

`make sample-env` writes a `.env` that sets the two keys the API cannot start without and leaves
every paid provider unset.
"""

GROUPS: Final = (
    ("Application", ("APP_ENV", "LOG_")),
    ("Database", ("DATABASE_",)),
    ("Authentication", ("AUTH_", "OTP_", "SMS_", "TRUSTED_PROXY_")),
    ("Realtime speech and voices", ("SPEECH_",)),
    ("Privacy", ("TRANSCRIPT_",)),
    ("Call transport", ("TELEPHONY_", "CALL_")),
    ("Language model", ("LLM_",)),
    ("Push notifications", ("APNS_", "FCM_")),
)


def variable(name: str) -> str:
    """The environment variable a field is read from: its name, upper-cased, with no prefix."""
    return name.upper()


def enum_values(annotation: object) -> tuple[str, ...]:
    """The values an enumerated field accepts, wherever the enum sits in its annotation."""
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return tuple(f"`{member.value}`" for member in annotation)
    return tuple(value for arg in get_args(annotation) for value in enum_values(arg))


def is_secret(annotation: object) -> bool:
    """Whether the field holds a `SecretStr`, alone or inside an optional or a tuple."""
    if annotation is SecretStr:
        return True
    return any(is_secret(arg) for arg in get_args(annotation))


def is_optional(annotation: object) -> bool:
    """Whether a blank value leaves the field unset."""
    return get_origin(annotation) in {Union, UnionType} and NoneType in get_args(annotation)


def accepted(field: FieldInfo) -> str:
    """What values a field accepts, when that is narrower than its type suggests."""
    values = enum_values(field.annotation)
    if values:
        return " or ".join(values) + (", or empty" if is_optional(field.annotation) else "")
    bounds = {Ge: "≥", Gt: ">", Le: "≤", Lt: "<"}
    limits = [
        f"{symbol} {getattr(item, kind.__name__.lower())}"
        for item in field.metadata
        for kind, symbol in bounds.items()
        if isinstance(item, kind)
    ]
    return ", ".join(limits)


def default(field: FieldInfo) -> str:
    """The default as it would be written in `.env`, or a dash for none."""
    value = field.default
    if value is None or value == ():
        return "—"
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, float) and value.is_integer():
        value = int(value)
    return f"`{value}`"


def required(field: FieldInfo) -> str:
    extra = field.json_schema_extra
    when = extra.get("required_when") if isinstance(extra, dict) else None
    return f"when {when}" if isinstance(when, str) else "no"


def cell(text: str) -> str:
    return text.replace("|", "\\|")


def reference(fields: dict[str, FieldInfo]) -> str:
    """The whole reference document, grouped the way `.env.example` is."""
    lines = [HEADER]
    placed: set[str] = set()
    for title, prefixes in GROUPS:
        names = [name for name in fields if variable(name).startswith(prefixes)]
        placed.update(names)
        lines += [
            f"## {title}",
            "",
            "| Variable | Required | Default | Accepts | Secret | Meaning |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for name in names:
            field = fields[name]
            lines.append(
                f"| `{variable(name)}` | {cell(required(field))} | {cell(default(field))} "
                f"| {cell(accepted(field))} | {'yes' if is_secret(field.annotation) else ''} "
                f"| {cell(field.description or '')} |"
            )
        lines.append("")
    lines += [
        "## The development stack",
        "",
        "Read by `make` and `docker-compose.yml`, not by the backend.",
        "",
        "| Variable | Meaning |",
        "| --- | --- |",
        *(f"| `{name}` | {meaning} |" for name, meaning in STACK_VARIABLES.items()),
        "",
    ]
    unplaced = sorted(set(fields) - placed)
    if unplaced:
        raise SystemExit(f"settings with no section in the reference: {unplaced}; add to GROUPS")
    return "\n".join(lines)


def assigned_in_env_example(text: str) -> set[str]:
    return set(re.findall(r"^([A-Z][A-Z0-9_]*)=", text, flags=re.MULTILINE))


def backend_environment_in_compose(text: str) -> set[str]:
    """The variable names under the backend service's `environment:` in the compose file.

    Read by indentation rather than with a YAML parser: the file's shape is fixed and simple, and
    a parser would be a dependency for one list of keys.
    """
    section = re.search(
        r"^  backend:\n(?:^    .*\n|^\s*\n)*?^    environment:\n((?:^      .*\n|^\s*\n)+)",
        text,
        flags=re.MULTILINE,
    )
    if section is None:
        raise SystemExit(f"{COMPOSE.name}: no environment for the backend service found")
    return set(re.findall(r"^      ([A-Z][A-Z0-9_]*):", section.group(1), flags=re.MULTILINE))


def differences(expected: set[str], found: set[str], where: str) -> list[str]:
    problems = []
    if missing := sorted(expected - found):
        problems.append(f"{where} does not list: {', '.join(missing)}")
    if extra := sorted(found - expected):
        problems.append(f"{where} lists what no setting reads: {', '.join(extra)}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on drift, write nothing")
    arguments = parser.parse_args()

    from letmehandle.config.settings import Settings

    fields = dict(Settings.model_fields)
    names = {variable(name) for name in fields}

    problems = [
        f"{variable(name)} has no description in Settings"
        for name, field in fields.items()
        if not field.description
    ]
    problems += differences(
        names | set(STACK_VARIABLES),
        assigned_in_env_example(ENV_EXAMPLE.read_text(encoding="utf-8")),
        ENV_EXAMPLE.name,
    )
    problems += differences(
        names,
        backend_environment_in_compose(COMPOSE.read_text(encoding="utf-8")),
        f"{COMPOSE.name}'s backend",
    )

    document = reference(fields)
    if arguments.check:
        current = REFERENCE.read_text(encoding="utf-8") if REFERENCE.exists() else ""
        if current != document:
            problems.append(
                f"{REFERENCE.relative_to(ROOT)} is out of date. Run: make config-reference"
            )
    else:
        REFERENCE.write_text(document, encoding="utf-8")
        print(f"wrote {REFERENCE.relative_to(ROOT)}")

    for problem in problems:
        print(f"configuration drift: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
