/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Answer without touching a dependency.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Answer whether every dependency this process needs is reachable.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a sign-in code
         * @description Send a code to a number, answering alike whether or not it has an account.
         */
        post: operations["request_challenge_v1_auth_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew a session
         * @description Exchange a refresh token for a new pair, retiring the old one (D-036).
         */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End this session
         * @description End this refresh token's session and forget the device on its account; always succeeds.
         */
        post: operations["sign_out_v1_auth_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a code
         * @description Exchange a correct code for a session, creating the account if there is not one.
         */
        post: operations["verify_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List calls
         * @description The user's calls, newest first; `from` inclusive and `to` exclusive, both with an offset.
         */
        get: operations["list_calls_v1_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report what happened to this handset's calls */
        post: operations["report_calls_v1_calls_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Open a call
         * @description One call in full: its summary, its timeline, and whether its transcript can still be read.
         */
        get: operations["read_call_v1_calls__call_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a call
         * @description Delete the call, its transcript and its summary, immediately. `204` even if already gone.
         */
        delete: operations["delete_call_v1_calls__call_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{call_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a call's transcript
         * @description What was said, while the user's retention still keeps it.
         */
        get: operations["read_transcript_v1_calls__call_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Register this device for escalation notifications
         * @description Record this device's push token for the signed-in user, idempotently.
         */
        put: operations["register_device_v1_devices_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop sending escalation notifications to this device
         * @description Forget this device for the signed-in user; a POST so the token stays out of access logs.
         */
        post: operations["unregister_device_v1_devices_unregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escalations/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The context of an escalation
         * @description What the user was, or would have been, told about this escalation.
         */
        get: operations["read_escalation_v1_escalations__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["read_me_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete the account
         * @description Delete the signed-in account and everything held for it, ending any call in progress.
         */
        delete: operations["delete_me_v1_me_delete"];
        options?: never;
        head?: never;
        /**
         * Update the profile
         * @description Change the fields sent and leave absent ones alone (D-023).
         */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where setup is */
        get: operations["read_onboarding_v1_onboarding_get"];
        put?: never;
        /**
         * Record a step
         * @description Record a step as answered or skipped; a step this deployment does not ask is refused.
         */
        post: operations["record_onboarding_step_v1_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read preferences */
        get: operations["read_preferences_v1_preferences_get"];
        /**
         * Replace preferences
         * @description Set everything the request mentions, starting from the defaults.
         */
        put: operations["replace_preferences_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change some of it
         * @description Change the sections that were sent and leave the rest exactly as they were (D-023).
         */
        patch: operations["update_preferences_v1_preferences_patch"];
        trace?: never;
    };
    "/v1/preferences/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The chosen voice */
        get: operations["read_selection_v1_preferences_voice_get"];
        /**
         * Choose a voice
         * @description Set or clear the chosen voice, refusing one the provider does not offer.
         */
        put: operations["choose_voice_v1_preferences_voice_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The voices on offer
         * @description What the configured provider offers, and what it can do with it.
         */
        get: operations["read_catalogue_v1_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthorityPayload
         * @description What the assistant may do on somebody's behalf. Everything opt-in.
         */
        AuthorityPayload: {
            /** Capabilities */
            capabilities?: components["schemas"]["Capability"][];
        };
        /**
         * CallDetailResponse
         * @description One call in full, with the user's current retention and when its transcript is due to go.
         */
        CallDetailResponse: {
            caller: components["schemas"]["CallerPayload"];
            /** Details */
            details: components["schemas"]["ExtractedDetailPayload"][];
            /** Duration Seconds */
            duration_seconds: number | null;
            escalation_reason: components["schemas"]["EscalationReason"] | null;
            handling: components["schemas"]["CallHandling"] | null;
            /** Headline */
            headline: string | null;
            /** Human Joined */
            human_joined: boolean;
            /** Id */
            id: string;
            importance: components["schemas"]["CallImportance"] | null;
            intent: components["schemas"]["CallIntent"] | null;
            outcome: components["schemas"]["CallOutcome"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["CallStatus"];
            timings: components["schemas"]["CallTimingsPayload"];
            /** Transcript Available */
            transcript_available: boolean;
            /** Transcript Expires At */
            transcript_expires_at: string | null;
            /** Transcript Retention Days */
            transcript_retention_days: number;
        };
        /**
         * CallEnding
         * @description How a reported call ended.
         * @enum {string}
         */
        CallEnding: "screened_out" | "missed" | "completed";
        /**
         * CallForwardingResponse
         * @description Where the user's phone should forward the calls it does not take.
         */
        CallForwardingResponse: {
            /**
             * Number
             * @description The number, in E.164 form, to set the phone's conditional call forwarding to: calls that go unanswered and calls that arrive while the line is busy.
             */
            number: string;
        };
        /**
         * CallHandling
         * @description Whom routing gave the call to, read from the moves the call made.
         * @enum {string}
         */
        CallHandling: "passed_through" | "assistant";
        /**
         * CallHandlingPayload
         * @description What happens to a call before anybody has spoken to it.
         */
        CallHandlingPayload: {
            anonymous_posture: components["schemas"]["HandlingPosture"];
            /** Blocked Categories */
            blocked_categories?: components["schemas"]["CallerCategory"][];
            default_posture: components["schemas"]["HandlingPosture"];
            escalate_at_or_above: components["schemas"]["CallImportance"];
            /** Posture By Category */
            posture_by_category?: {
                [key: string]: components["schemas"]["HandlingPosture"];
            };
        };
        /**
         * CallImportance
         * @description How much a call matters to the user, ordered, with gaps so a level can be inserted.
         * @enum {integer}
         */
        CallImportance: 10 | 20 | 30 | 40 | 50;
        /**
         * CallIntent
         * @description What the call is for; `UNDETERMINED` is the answer while there is none yet.
         * @enum {string}
         */
        CallIntent: "undetermined" | "delivery_in_progress" | "appointment" | "enquiry" | "personal" | "service_issue" | "sales" | "suspected_fraud";
        /**
         * CallListItem
         * @description One call in the list; `outcome` and `headline` are null until it has a summary.
         */
        CallListItem: {
            caller: components["schemas"]["CallerPayload"];
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Headline */
            headline: string | null;
            /** Human Joined */
            human_joined: boolean;
            /** Id */
            id: string;
            outcome: components["schemas"]["CallOutcome"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["CallStatus"];
        };
        /**
         * CallOutcome
         * @description How a call ended in the terms a person would use, unlike the mechanism of `CallState`.
         * @enum {string}
         */
        CallOutcome: "resolved_by_agent" | "handed_to_user" | "passed_through" | "rejected_by_rule" | "caller_hung_up" | "unanswered_escalation" | "failed";
        /** CallPageResponse */
        CallPageResponse: {
            /** Calls */
            calls: components["schemas"]["CallListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CallReportBatch */
        CallReportBatch: {
            /** Reports */
            reports: components["schemas"]["CallReportPayload"][];
        };
        /** CallReportPayload */
        CallReportPayload: {
            /** Call Id */
            call_id: string;
            /** Caller Number */
            caller_number?: string | null;
            ending?: components["schemas"]["CallEnding"] | null;
            /** Event Id */
            event_id: string;
            kind: components["schemas"]["ReportedCallKind"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            screening?: components["schemas"]["ScreeningDecision"] | null;
        };
        /**
         * CallReportReceipt
         * @description What became of each report in a batch; the handset forgets every one listed.
         */
        CallReportReceipt: {
            /** Accepted */
            accepted: string[];
            /** Duplicates */
            duplicates: string[];
            /** Rejected */
            rejected: components["schemas"]["RejectedReport"][];
        };
        /**
         * CallStatus
         * @description Whether a call is still going.
         * @enum {string}
         */
        CallStatus: "in_progress" | "ended";
        /**
         * CallTimingsPayload
         * @description When each thing happened. A step that never happened is null.
         */
        CallTimingsPayload: {
            /** Answered At */
            answered_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Escalated At */
            escalated_at: string | null;
            /** Human Joined At */
            human_joined_at: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /**
         * CallerCategory
         * @description The coarse kinds of call the user's rules act on.
         * @enum {string}
         */
        CallerCategory: "known_contact" | "delivery" | "healthcare" | "education" | "financial" | "service_provider" | "sales" | "spam" | "unknown";
        /** CallerPayload */
        CallerPayload: {
            category: components["schemas"]["CallerCategory"];
            /** Display Name */
            display_name: string | null;
            /** Number Withheld */
            number_withheld: boolean;
        };
        /**
         * Capability
         * @description One thing the assistant may be permitted to do, each a decision a user makes on its own.
         * @enum {string}
         */
        Capability: "answer_questions_about_availability" | "share_delivery_instructions" | "confirm_appointments" | "reschedule_appointments" | "decline_on_the_users_behalf" | "take_a_message" | "share_contact_details";
        /** ChallengeRequest */
        ChallengeRequest: {
            /** Phone Number */
            phone_number: string;
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /** Challenge Id */
            challenge_id: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Resend After Seconds */
            resend_after_seconds: number;
        };
        /**
         * DevicePayload
         * @description One device, as its platform identifies it.
         */
        DevicePayload: {
            platform: components["schemas"]["DevicePlatform"];
            /** Token */
            token: string;
        };
        /**
         * DevicePlatform
         * @description Which delivery path a device needs.
         * @enum {string}
         */
        DevicePlatform: "ios" | "android";
        /**
         * EscalationContextResponse
         * @description An escalation as the app shows it: the untrimmed notification words and their fields.
         */
        EscalationContextResponse: {
            /** Body */
            body: string;
            /** Call Id */
            call_id: string;
            /** Caller */
            caller: string | null;
            /** Caller Label */
            caller_label: string;
            delivery: components["schemas"]["NotificationDelivery"];
            /** Ended At */
            ended_at: string | null;
            /** Established */
            established: string | null;
            /** Needed */
            needed: string | null;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            reason: components["schemas"]["EscalationReason"];
            status: components["schemas"]["EscalationStatus"];
            /** Title */
            title: string;
        };
        /**
         * EscalationReason
         * @description Why the assistant wants the user.
         * @enum {string}
         */
        EscalationReason: "caller_asked_for_the_user" | "action_not_authorised" | "decision_needs_the_user" | "important_enough_to_interrupt" | "cannot_understand_the_caller" | "user_rule_requires_it";
        /**
         * EscalationStatus
         * @description Whether the call the escalation belongs to is still going.
         * @enum {string}
         */
        EscalationStatus: "live" | "ended";
        /** ExtractedDetailPayload */
        ExtractedDetailPayload: {
            /** Evidence */
            evidence: string | null;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * Formality
         * @description How the assistant should sound.
         * @enum {string}
         */
        Formality: "warm" | "neutral" | "formal";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HandlingPosture
         * @description What should happen to a call before anyone has spoken to it.
         * @enum {string}
         */
        HandlingPosture: "pass_through" | "handle_with_agent" | "reject";
        /**
         * Health
         * @description Liveness: is this process running.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * HoursPayload
         * @description When the assistant answers; outside it, calls ring the user. `null` is always (D-030).
         */
        HoursPayload: {
            active?: components["schemas"]["TimeWindowPayload"] | null;
        };
        /** ImportantContactPayload */
        ImportantContactPayload: {
            /** Label */
            label: string;
            /** Phone Number */
            phone_number: string;
            /** @default pass_through */
            posture: components["schemas"]["HandlingPosture"];
        };
        /**
         * NotificationDelivery
         * @description What became of telling the user, surfaced in the app rather than raised anywhere.
         * @enum {string}
         */
        NotificationDelivery: "pending" | "delivered" | "failed" | "no_devices";
        /** NotificationsPayload */
        NotificationsPayload: {
            /**
             * Daily Summary
             * @default false
             */
            daily_summary: boolean;
            /**
             * On Blocked Call
             * @default false
             */
            on_blocked_call: boolean;
            /**
             * On Handled Call
             * @default false
             */
            on_handled_call: boolean;
            /**
             * On Missed Escalation
             * @default true
             */
            on_missed_escalation: boolean;
            /**
             * Respect Active Hours
             * @default true
             */
            respect_active_hours: boolean;
        };
        /**
         * OnboardingResponse
         * @description Where somebody is in the flow, listing only the steps this deployment asks, in order.
         */
        OnboardingResponse: {
            /** Completed */
            completed: components["schemas"]["OnboardingStep"][];
            /** Is Complete */
            is_complete: boolean;
            next_step: components["schemas"]["OnboardingStep"] | null;
            /** Remaining */
            remaining: components["schemas"]["OnboardingStep"][];
            /** Skipped */
            skipped: components["schemas"]["OnboardingStep"][];
        };
        /**
         * OnboardingStep
         * @description One screen of setup, asking about one group of preferences.
         * @enum {string}
         */
        OnboardingStep: "call_handling" | "call_forwarding" | "hours" | "authority" | "notifications";
        /** OnboardingUpdate */
        OnboardingUpdate: {
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            step: components["schemas"]["OnboardingStep"];
        };
        /** PersonalityPayload */
        PersonalityPayload: {
            /** Disclosable Facts */
            disclosable_facts?: string[];
            /** @default neutral */
            formality: components["schemas"]["Formality"];
            /** Topics */
            topics?: string[];
            /** @default normal */
            verbosity: components["schemas"]["Verbosity"];
        };
        /**
         * PreferencesResponse
         * @description Everything, as it stands.
         */
        PreferencesResponse: {
            authority: components["schemas"]["AuthorityPayload"];
            call_handling: components["schemas"]["CallHandlingPayload"];
            hours: components["schemas"]["HoursPayload"];
            /** Important Contacts */
            important_contacts: components["schemas"]["ImportantContactPayload"][];
            /** Locale */
            locale: string;
            notifications: components["schemas"]["NotificationsPayload"];
            personality: components["schemas"]["PersonalityPayload"];
            privacy: components["schemas"]["PrivacyResponse"];
            /** Version */
            version: number;
        };
        /**
         * PreferencesUpdate
         * @description A change to some of it; an omitted section is left exactly as it was.
         */
        PreferencesUpdate: {
            authority?: components["schemas"]["AuthorityPayload"] | null;
            call_handling?: components["schemas"]["CallHandlingPayload"] | null;
            hours?: components["schemas"]["HoursPayload"] | null;
            /** Important Contacts */
            important_contacts?: components["schemas"]["ImportantContactPayload"][] | null;
            /** Locale */
            locale?: string | null;
            notifications?: components["schemas"]["NotificationsPayload"] | null;
            personality?: components["schemas"]["PersonalityPayload"] | null;
            privacy?: components["schemas"]["PrivacyPayload"] | null;
        };
        /**
         * PrivacyPayload
         * @description What is kept, and for how long.
         */
        PrivacyPayload: {
            /** Transcript Retention Days */
            transcript_retention_days: number;
        };
        /**
         * PrivacyResponse
         * @description What is kept, and for how long, as stored and unbounded above.
         */
        PrivacyResponse: {
            /** Transcript Retention Days */
            transcript_retention_days: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** @description Present when calls reach the assistant only by being forwarded: until the user's phone forwards unanswered and busy calls to this number, no call reaches it. Null when nothing needs forwarding. */
            call_forwarding: components["schemas"]["CallForwardingResponse"] | null;
            /** Display Name */
            display_name: string | null;
            /** Id */
            id: string;
            /** Locale */
            locale: string;
            /** Phone Number */
            phone_number: string;
        };
        /**
         * Readiness
         * @description Readiness: each dependency's answer, each circuit by role, and how limits are counted.
         */
        Readiness: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Dependencies */
            dependencies: {
                [key: string]: "closed" | "open" | "half_open";
            };
            /**
             * Rate Limits
             * @enum {string}
             */
            rate_limits: "shared" | "per_process";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterDeviceRequest
         * @description This device's current push token, and the one the platform rotated away from if known.
         */
        RegisterDeviceRequest: {
            platform: components["schemas"]["DevicePlatform"];
            /** Previous Token */
            previous_token?: string | null;
            /** Token */
            token: string;
        };
        /**
         * RejectedReport
         * @description A report that was not stored, and will not be however often it is sent.
         */
        RejectedReport: {
            /** Event Id */
            event_id: string | null;
            /** Index */
            index: number;
            /** Reason */
            reason: string;
        };
        /**
         * ReportedCallKind
         * @description What a handset can observe about its own call. Nothing joins or leaves one visibly.
         * @enum {string}
         */
        ReportedCallKind: "incoming" | "answered" | "ended";
        /**
         * ScreeningDecision
         * @description What was done with a call before the handset rang, where screening is declared.
         * @enum {string}
         */
        ScreeningDecision: "allow" | "reject" | "silence";
        /** SignOutRequest */
        SignOutRequest: {
            device?: components["schemas"]["DevicePayload"] | null;
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Speaker
         * @description Who said something.
         * @enum {string}
         */
        Speaker: "caller" | "agent" | "human";
        /**
         * TimeWindowPayload
         * @description A daily window, with the zone it is read in.
         */
        TimeWindowPayload: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Zone */
            zone: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** TranscriptLinePayload */
        TranscriptLinePayload: {
            /**
             * Said At
             * Format: date-time
             */
            said_at: string;
            speaker: components["schemas"]["Speaker"];
            /** Text */
            text: string;
        };
        /**
         * TranscriptResponse
         * @description What remains of a call's transcript, in the order it was said, and when it goes.
         */
        TranscriptResponse: {
            /** Call Id */
            call_id: string;
            /** Entries */
            entries: components["schemas"]["TranscriptLinePayload"][];
            /** Transcript Expires At */
            transcript_expires_at: string | null;
            /** Transcript Retention Days */
            transcript_retention_days: number;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Locale */
            locale?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verbosity
         * @description How much the assistant says, independently of how formally.
         * @enum {string}
         */
        Verbosity: "brief" | "normal" | "detailed";
        /** VerifyRequest */
        VerifyRequest: {
            /** Challenge Id */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * VoiceCapabilitiesPayload
         * @description What the configured provider can do; a control it cannot serve is not drawn.
         */
        VoiceCapabilitiesPayload: {
            /** Builtin Voices */
            builtin_voices: boolean;
            /** Cloning */
            cloning: boolean;
            /** Custom Voice */
            custom_voice: boolean;
            /** Local Inference */
            local_inference: boolean;
            /** Preview */
            preview: boolean;
            /** Realtime Streaming */
            realtime_streaming: boolean;
        };
        /**
         * VoiceCatalogueResponse
         * @description Everything a client needs to draw the voice screen.
         */
        VoiceCatalogueResponse: {
            capabilities: components["schemas"]["VoiceCapabilitiesPayload"];
            /** Default Voice Id */
            default_voice_id: string;
            /** Provider */
            provider: string;
            /** Voices */
            voices: components["schemas"]["VoicePayload"][];
        };
        /**
         * VoicePayload
         * @description One voice, and whether this one in particular can be heard.
         */
        VoicePayload: {
            /** Id */
            id: string;
            /** Locales */
            locales: string[];
            /** Name */
            name: string;
            /** Previewable */
            previewable: boolean;
        };
        /**
         * VoiceSelectionResponse
         * @description What the user has chosen, and the voice the fallback chain resolves to now.
         */
        VoiceSelectionResponse: {
            /** Cloned Voice Id */
            cloned_voice_id: string | null;
            /** Persona Voice Id */
            persona_voice_id: string | null;
            /** Resolved Voice Id */
            resolved_voice_id: string;
        };
        /**
         * VoiceSelectionUpdate
         * @description A change to the chosen voice: required, with `null` returning to the provider's default.
         */
        VoiceSelectionUpdate: {
            /** Persona Voice Id */
            persona_voice_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    request_challenge_v1_auth_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_v1_auth_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignOutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_v1_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                outcome?: components["schemas"]["CallOutcome"] | null;
                from?: string | null;
                to?: string | null;
                human_joined?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_calls_v1_calls_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallReportBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallReportReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_call_v1_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_call_v1_calls__call_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_transcript_v1_calls__call_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_v1_devices_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_device_v1_devices_unregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_escalation_v1_escalations__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    delete_me_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_onboarding_v1_onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
        };
    };
    record_onboarding_step_v1_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_preferences_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    replace_preferences_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_v1_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_selection_v1_preferences_voice_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSelectionResponse"];
                };
            };
        };
    };
    choose_voice_v1_preferences_voice_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSelectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSelectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_catalogue_v1_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceCatalogueResponse"];
                };
            };
        };
    };
}
