/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Answer without touching a dependency.
         *
         *     An orchestrator restarts a process that fails this. Checking the database here would make
         *     a database outage restart every healthy process, which turns an outage into a worse one.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Answer whether every dependency this process needs is reachable.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a sign-in code
         * @description Send a code to a number.
         *
         *     Answers the same way whether or not the number has an account. Telling them apart is the
         *     expensive half of attacking a phone-number identity, and this is where it would be given
         *     away for nothing.
         */
        post: operations["request_challenge_v1_auth_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew a session
         * @description Exchange a refresh token for a new pair.
         *
         *     The old one stops working immediately. Presenting it again means a copy exists somewhere
         *     it should not, and every session from that sign-in ends.
         */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End this session
         * @description End the session this refresh token belongs to.
         *
         *     Always succeeds. Somebody signing out has nothing to gain from being told their token was
         *     already invalid, and saying so would tell an attacker whether a token they hold is real.
         */
        post: operations["sign_out_v1_auth_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a code
         * @description Exchange a correct code for a session, creating the account if there is not one.
         */
        post: operations["verify_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["read_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the profile
         * @description Change what the assistant knows about the person it represents.
         *
         *     A field that is absent is left alone rather than cleared. A client sending only what it
         *     changed is the ordinary case, and reading absence as "set to nothing" would quietly erase
         *     everything it did not mention.
         */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where setup is */
        get: operations["read_onboarding_v1_onboarding_get"];
        put?: never;
        /**
         * Record a step
         * @description Record a step as answered, or deliberately passed over.
         *
         *     Held here rather than on the device, so that reinstalling or signing in elsewhere resumes
         *     where somebody was instead of asking them everything again.
         */
        post: operations["record_onboarding_step_v1_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read preferences */
        get: operations["read_preferences_v1_preferences_get"];
        /**
         * Replace preferences
         * @description Set everything the request mentions, from the defaults.
         *
         *     Distinct from the patch below: this starts from the defaults rather than from what is
         *     stored, so a section left out is reset rather than kept. That is what a client means when
         *     it says "replace".
         */
        put: operations["replace_preferences_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change some of it
         * @description Change the sections that were sent and leave the rest exactly as they were.
         *
         *     The ordinary case: one screen saves one section, and has no idea what the others hold.
         */
        patch: operations["update_preferences_v1_preferences_patch"];
        trace?: never;
    };
    "/v1/preferences/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The chosen voice */
        get: operations["read_selection_v1_preferences_voice_get"];
        /**
         * Choose a voice
         * @description Set or clear the chosen voice.
         *
         *     A voice the provider does not offer is refused rather than stored. Storing it would
         *     mean a selection that silently falls through to the default on every call, which looks
         *     to the user exactly like their choice being ignored.
         *
         *     Only the half this request is about is sent. The cloned voice is left to the service to
         *     carry, under the lock it takes: read here instead, a clone revoked while this request
         *     was in flight would be written back from a read taken before it.
         */
        put: operations["choose_voice_v1_preferences_voice_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The voices on offer
         * @description What the configured provider offers, and what it can do with it.
         *
         *     The client renders from this rather than from a bundled list, so a deployment that
         *     changes provider changes the screen without shipping an app.
         *
         *     Behind a token like everything else: this is a signed-in screen, and which provider a
         *     deployment runs is not something to tell whoever asks.
         */
        get: operations["read_catalogue_v1_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthorityPayload
         * @description What the assistant may do on somebody's behalf. Everything opt-in.
         */
        AuthorityPayload: {
            /** Capabilities */
            capabilities?: components["schemas"]["Capability"][];
        };
        /**
         * CallHandlingPayload
         * @description What happens to a call before anybody has spoken to it.
         */
        CallHandlingPayload: {
            anonymous_posture: components["schemas"]["HandlingPosture"];
            /** Blocked Categories */
            blocked_categories?: components["schemas"]["CallerCategory"][];
            default_posture: components["schemas"]["HandlingPosture"];
            escalate_at_or_above: components["schemas"]["CallImportance"];
            /** Posture By Category */
            posture_by_category?: {
                [key: string]: components["schemas"]["HandlingPosture"];
            };
        };
        /**
         * CallImportance
         * @description How much this matters to the user, ordered.
         *
         *     An `IntEnum` because these are compared — a rule says "escalate at or above this" — and an
         *     ordering written as a lookup table beside an unordered enum is an ordering that drifts
         *     from it.
         *
         *     The numbers are spaced so that a level can be inserted later without renumbering the ones
         *     either side, which would silently change the meaning of every stored value.
         * @enum {integer}
         */
        CallImportance: 10 | 20 | 30 | 40 | 50;
        /**
         * CallerCategory
         * @description What kind of call this appears to be.
         *
         *     Deliberately coarse. These are the distinctions the user's rules act on — the difference
         *     between a delivery and a courier is not one anybody would set a different rule for, and a
         *     category nobody can act on is a category that only makes classification harder.
         * @enum {string}
         */
        CallerCategory: "known_contact" | "delivery" | "healthcare" | "education" | "financial" | "service_provider" | "sales" | "spam" | "unknown";
        /**
         * Capability
         * @description One thing the assistant may be permitted to do.
         *
         *     Each is a distinct decision a user would actually make differently, which is the test for
         *     whether a capability belongs here. Splitting further produces a settings screen nobody
         *     finishes; merging produces permissions nobody meant to give.
         * @enum {string}
         */
        Capability: "answer_questions_about_availability" | "share_delivery_instructions" | "confirm_appointments" | "reschedule_appointments" | "decline_on_the_users_behalf" | "take_a_message" | "share_contact_details";
        /** ChallengeRequest */
        ChallengeRequest: {
            /** Phone Number */
            phone_number: string;
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /** Challenge Id */
            challenge_id: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /**
         * Formality
         * @description How the assistant should sound.
         * @enum {string}
         */
        Formality: "warm" | "neutral" | "formal";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HandlingPosture
         * @description What should happen to a call before anyone has spoken to it.
         * @enum {string}
         */
        HandlingPosture: "pass_through" | "handle_with_agent" | "reject";
        /**
         * Health
         * @description Liveness: is this process running.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HoursPayload */
        HoursPayload: {
            quiet?: components["schemas"]["TimeWindowPayload"] | null;
            working?: components["schemas"]["TimeWindowPayload"] | null;
        };
        /** ImportantContactPayload */
        ImportantContactPayload: {
            /** Label */
            label: string;
            /** Phone Number */
            phone_number: string;
            /** @default pass_through */
            posture: components["schemas"]["HandlingPosture"];
        };
        /** NotificationsPayload */
        NotificationsPayload: {
            /**
             * Daily Summary
             * @default false
             */
            daily_summary: boolean;
            /**
             * On Blocked Call
             * @default false
             */
            on_blocked_call: boolean;
            /**
             * On Handled Call
             * @default false
             */
            on_handled_call: boolean;
            /**
             * On Missed Escalation
             * @default true
             */
            on_missed_escalation: boolean;
            /**
             * Respect Quiet Hours
             * @default true
             */
            respect_quiet_hours: boolean;
        };
        /**
         * OnboardingResponse
         * @description Where somebody is in the flow, and what is left.
         */
        OnboardingResponse: {
            /** Completed */
            completed: components["schemas"]["OnboardingStep"][];
            /** Is Complete */
            is_complete: boolean;
            next_step: components["schemas"]["OnboardingStep"] | null;
            /** Remaining */
            remaining: components["schemas"]["OnboardingStep"][];
            /** Skipped */
            skipped: components["schemas"]["OnboardingStep"][];
        };
        /**
         * OnboardingStep
         * @description One thing to ask about.
         *
         *     One step per group of preferences, because a step is a screen and a screen that asks about
         *     two unrelated things is one people abandon.
         * @enum {string}
         */
        OnboardingStep: "introduction" | "call_handling" | "important_contacts" | "hours" | "authority" | "notifications" | "personality";
        /** OnboardingUpdate */
        OnboardingUpdate: {
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            step: components["schemas"]["OnboardingStep"];
        };
        /** PersonalityPayload */
        PersonalityPayload: {
            /** Disclosable Facts */
            disclosable_facts?: string[];
            /** @default neutral */
            formality: components["schemas"]["Formality"];
            /** Topics */
            topics?: string[];
            /** @default normal */
            verbosity: components["schemas"]["Verbosity"];
        };
        /**
         * PreferencesResponse
         * @description Everything, as it stands.
         */
        PreferencesResponse: {
            authority: components["schemas"]["AuthorityPayload"];
            call_handling: components["schemas"]["CallHandlingPayload"];
            hours: components["schemas"]["HoursPayload"];
            /** Important Contacts */
            important_contacts: components["schemas"]["ImportantContactPayload"][];
            /** Locale */
            locale: string;
            notifications: components["schemas"]["NotificationsPayload"];
            personality: components["schemas"]["PersonalityPayload"];
            privacy: components["schemas"]["PrivacyPayload"];
            /** Version */
            version: number;
        };
        /**
         * PreferencesUpdate
         * @description A change to some of it.
         *
         *     Every section is optional, and an omitted section is left exactly as it was. That is what
         *     lets one screen save one section without knowing or caring what the others hold.
         */
        PreferencesUpdate: {
            authority?: components["schemas"]["AuthorityPayload"] | null;
            call_handling?: components["schemas"]["CallHandlingPayload"] | null;
            hours?: components["schemas"]["HoursPayload"] | null;
            /** Important Contacts */
            important_contacts?: components["schemas"]["ImportantContactPayload"][] | null;
            /** Locale */
            locale?: string | null;
            notifications?: components["schemas"]["NotificationsPayload"] | null;
            personality?: components["schemas"]["PersonalityPayload"] | null;
            privacy?: components["schemas"]["PrivacyPayload"] | null;
        };
        /**
         * PrivacyPayload
         * @description What is kept, and for how long.
         */
        PrivacyPayload: {
            /**
             * Transcript Retention Days
             * @default 7
             */
            transcript_retention_days: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Display Name */
            display_name: string | null;
            /** Id */
            id: string;
            /** Locale */
            locale: string;
            /** Phone Number */
            phone_number: string;
        };
        /**
         * Readiness
         * @description Readiness: can this process do its job.
         *
         *     ``checks`` names each dependency and whether it answered. It carries no configuration —
         *     not a host, not a user, not a URL — because a readiness endpoint is usually the most
         *     exposed thing an application has.
         */
        Readiness: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SignOutRequest */
        SignOutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * TimeWindowPayload
         * @description A daily window, in the user's own zone.
         *
         *     The zone travels with the window rather than being applied later. A window compared in the
         *     wrong zone is off by hours, and the mistake shows up as calls handled at the wrong time of
         *     day rather than as anything that looks like a bug.
         */
        TimeWindowPayload: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Zone */
            zone: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Locale */
            locale?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verbosity
         * @description How much the assistant says.
         *
         *     Separate from formality because they vary independently: a warm assistant can be brief, and
         *     a formal one can go on. Collapsing them into one dial would make half the combinations
         *     people actually want unreachable.
         * @enum {string}
         */
        Verbosity: "brief" | "normal" | "detailed";
        /** VerifyRequest */
        VerifyRequest: {
            /** Challenge Id */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * VoiceCapabilitiesPayload
         * @description What the configured provider can do.
         *
         *     The interface renders from these. Everything absent means the control is not drawn at all —
         *     not disabled, not labelled as unavailable — because a control that cannot work teaches
         *     people to distrust the ones that can.
         */
        VoiceCapabilitiesPayload: {
            /** Builtin Voices */
            builtin_voices: boolean;
            /** Cloning */
            cloning: boolean;
            /** Custom Voice */
            custom_voice: boolean;
            /** Local Inference */
            local_inference: boolean;
            /** Preview */
            preview: boolean;
            /** Realtime Streaming */
            realtime_streaming: boolean;
        };
        /**
         * VoiceCatalogueResponse
         * @description Everything a client needs to draw the voice screen.
         */
        VoiceCatalogueResponse: {
            capabilities: components["schemas"]["VoiceCapabilitiesPayload"];
            /** Default Voice Id */
            default_voice_id: string;
            /** Provider */
            provider: string;
            /** Voices */
            voices: components["schemas"]["VoicePayload"][];
        };
        /**
         * VoicePayload
         * @description One voice, and whether this one in particular can be heard.
         *
         *     Per voice rather than per provider: a provider holding a sample for one voice and not
         *     another declares the capability and can still serve only the one, and a client drawing a
         *     control from the capability alone draws two that fail.
         */
        VoicePayload: {
            /** Id */
            id: string;
            /** Locales */
            locales: string[];
            /** Name */
            name: string;
            /** Previewable */
            previewable: boolean;
        };
        /**
         * VoiceSelectionResponse
         * @description What the user has chosen, and what a call would actually use.
         *
         *     `resolved_voice_id` is the answer the fallback chain gives right now — the cloned voice if
         *     it is still available, otherwise the chosen one, otherwise the provider's default. It is
         *     returned alongside the choice because those differ exactly when something has gone wrong
         *     with a voice, and that is the moment a user should be able to see it.
         */
        VoiceSelectionResponse: {
            /** Cloned Voice Id */
            cloned_voice_id: string | null;
            /** Persona Voice Id */
            persona_voice_id: string | null;
            /** Resolved Voice Id */
            resolved_voice_id: string;
        };
        /**
         * VoiceSelectionUpdate
         * @description A change to the chosen voice.
         *
         *     The field is required and may be `null`, and the difference from optional is the point.
         *     `null` clears the choice and returns to the provider's default, which somebody must be able
         *     to do; a request that simply left the field out would otherwise mean the same thing, and a
         *     client reading the schema could not tell "clear it" from "I forgot to send it".
         */
        VoiceSelectionUpdate: {
            /** Persona Voice Id */
            persona_voice_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    request_challenge_v1_auth_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_v1_auth_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignOutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_onboarding_v1_onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
        };
    };
    record_onboarding_step_v1_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_preferences_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    replace_preferences_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_v1_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_selection_v1_preferences_voice_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSelectionResponse"];
                };
            };
        };
    };
    choose_voice_v1_preferences_voice_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSelectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSelectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_catalogue_v1_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceCatalogueResponse"];
                };
            };
        };
    };
}
